export type MangaResolveErrorCode =
  | 'MANGA_INVALID_REQUEST'
  | 'MANGA_SOURCE_NOT_ALLOWED'
  | 'MANGA_RESOLVE_TITLE_NOT_FOUND'
  | 'MANGA_INSTANCE_NOT_FOUND'
  | 'MANGA_CANDIDATE_NOT_FOUND'
  | 'MANGA_ITEM_NOT_FOUND'
  | 'MANGA_ALREADY_BOUND'
  | 'MANGA_CANDIDATE_GONE'
  | 'MANGA_ITEM_BOUND_ELSEWHERE'
  | 'MANGA_UNSUPPORTED_SERVER'
  | 'MANGA_INSTANCE_CHANGED'
  | 'MANGA_ITEM_CHANGED'
  | 'MANGA_UNIQUE_CONFLICT'
  | 'MANGA_SUWAYOMI_LOOKUP_FAILED';

/** Why a title has its status. */
export type MangaResolveReason =
  // BOUND
  | 'EXACT_LINK'
  | 'EXISTING_BINDING'
  | 'ADMIN_BIND'
  // NEEDS_PICK
  | 'MANGADEX_AMBIGUOUS'
  | 'EXACT_IN_LIBRARY'
  | 'EXACT_BOUND_ELSEWHERE'
  | 'EXACT_REJECTED'
  | 'EXACT_NOT_PREFERRED'
  | 'EXACT_BY_TITLE'
  | 'TITLE_MATCHES'
  // NO_MATCH
  | 'NO_CANDIDATES'
  | 'NO_ELIGIBLE_SOURCES'
  | 'MANGADEX_FAILED'
  // EXCLUDED
  | 'CONTENT_POLICY'
  | 'ANILIST_NOT_FOUND';

/** What went wrong in a title's last run. */
export type MangaResolveFailure =
  | 'ANILIST_FAILED'
  | 'ANILIST_RATE_LIMITED'
  | 'MANGADEX_COOLDOWN'
  | 'MANGADEX_FAILED'
  | 'SOURCE_SEARCH_FAILED'
  | 'SUWAYOMI_UNAVAILABLE'
  | 'BIND_FAILED';
